monolog:
    handlers:
        main:
            type: stream
            #path: "%kernel.logs_dir%/%kernel.environment%.log"
            path: "%kernel.logs_dir%/deeeeeeev.log"
            level: debug
        console_exceptions_handler:
            type: stream
            path: "%kernel.logs_dir%/dev_CONSOLE_EXCEPTIONS.log"
            level: debug
            channels: ['console_exceptions_listener']
        runtime_exceptions_handler:
            type: stream
            path: "%kernel.logs_dir%/dev_RUNTIME_EXCEPTIONS.log"
            level: debug
            channels: ['runtime_exceptions_listener']
        # uncomment to get logging in your browser
        # you may have to allow bigger header sizes in your Web server configuration
        #firephp:
        #    type: firephp
        #    level: info
        #chromephp:
        #    type: chromephp
        #    level: info
        console:
            type: console
            level: debug
            process_psr_3_messages: false
            channels: ["!event"]
            verbosity_levels:
                VERBOSITY_NORMAL: DEBUG
